### ISSUE TITLE
Custom scrollbars do not seem to work on nightly 63

### ISSUE THREAD

**Issue by nyggidy** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#14]
I'm pretty sure I followed the instructions correctly to modify the scrollbars and yet the they won't change after restarting Firefox.

**Comment by Izheil** [comment]
To see if you placed the files right, check if any of the other javascript files work, like the tooltips or the multi-row ones. They should only work if you patched firefox root folder with the files inside the <code>scrollbars & tooltips/root</code> folder.
The profile folder files should go inside the chrome folder.
If you still can't make it work, tell me your OS, and tell me if userchrome or usercontent work at least.

**Comment by nyggidy** [comment]
The scrollbars appeared after an hour of browsing, really weird. I guess you can close this issue.

**Comment by Izheil** [comment]
Odd, maybe it was the cache or something. 
Anyway, glad to hear it got solved! I'm closing the issue now.
