### ISSUE TITLE
Old scrollbars patcher no longer working

### ISSUE THREAD

**Issue by jesseruley** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#15]
Old scrollbars method doesn't seem to work with latest firefox update (61.0). It just removes the scrollbars entirely. Removing the line from chrome.manifest obviously reverts to stock scrollbars still.

The normal method for changing scrollbars doesn't work for me, so I'm hoping there's a fix for the old method

**Comment by Izheil** [comment]
Both methods still work, make sure to use the updated scrollbar CSS files from the new method if you are using the old (But you should just try to make the new method work instead, the old one is not permanent), and place the scrollbars CSS file in the same place where the manifest file is (not in the chrome folder).

For the new method, make sure you placed the files in the right place. The files inside the "root" in here should go inside <code>C:\Program Files\Mozilla Firefox\</code> for Windows, <code>/usr/lib/firefox/</code> for linux, or <code>/Applications/Firefox.app/Contents/Resources</code> for MacOS.
After that you'd just have to place the other files (the ones inside "profile") inside your chrome folder.

**Comment by jesseruley** [comment]
Copying the CSS from the updated scrollbars.uc.js file into the scrollbars.css file works. Thanks

I'll stick with this method because I can't get the normal one to work. I've tried a few times with no success, and this one seems easy enough

**Comment by Izheil** [comment]
Hmm... Some file must be misplaced, I'm using the new method and it still works, so I'm not sure as of why it wouldn't for you.
I made a guide video a while ago, if you still want to give it a last try for the new method, you can check it here: <a href="https://youtu.be/z0o8DatRyjk?t=1m59s">https://youtu.be/z0o8DatRyjk?t=1m59s</a>

**Comment by jesseruley** [comment]
Just skimmed the video and that is indeed the same procedure I went through.
I have [ShadowFox](https://github.com/overdodactyl/ShadowFox) installed, so it's possible there is some conflict between the two which doesn't allow the scrollbars to take effect. 
I have tried uninstalling ShadowFox and trying to get the scrollbars to work, but still no success.

Anyways, thanks for the help
