### ISSUE TITLE
changing min-width in MultiRowTabLiteforFx.uc.js does not change min tab width

### ISSUE THREAD

**Issue by geekzer0** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#18]
First, THANK YOU for this!  The only thing I'd like is bigger default tab width, it looks to fitting 32 tabs by default.  Changing min-width (and purging the cache folder) doesn't change appearances at all.

Again THANK YOU for this extension!

**Comment by Izheil** [comment]
Thank you for trying it!
The problem happens because there is a missing !important, so the code should be like like:

<pre>
.tabbrowser-tab:not([pinned]) {
    flex-grow:1;
    min-width:100px !important}
</pre>

I'll update it right now, thanks for noting it!

**Comment by geekzer0** [comment]
Awesome yes that fixed it!  thanks so much
