### ISSUE TITLE
Sidebar is not themed

### ISSUE THREAD

**Issue by hakerdefo** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#2]
First kudos on great work @Izheil !!!
Everything working great after adding **userChrome.css** & **userContent.css** into the Firefox profile folder. Only thing that doesn't look part of the theme is the **sidebar**. They say a picture is worth a thousand words so here it goes,
[Shot-301117-021845.png](https://i.imgur.com/JqHvJbl.png)
It will be great if you can fix this.
Cheers!!!

**Comment by Izheil** [comment]
Thanks! 
I've looked into the sidebar issue, and **it's fixed** now. I even included the option to hide completelly the sidebar resizing it to the left. This will be on by default (that way you don't need to keep the sidebar button on the toolbar after activating it once).

**Comment by hakerdefo** [comment]
@Izheil Great!
Your work has allowed me to carry on using my favorite theme **BlackMate** in **PCLinuxOS** Mate edition. Before applying your theme, Many components of Firefox (Main Menu for example) were almost unreadable with **BlackMate** theme. Thanks again!
Cheers!!!

**Comment by Izheil** [comment]
Glad to know it's going good! 

I had some issue with some OS theme as well (it would turn the search boxes background black... but leaving the letters black), so I thought it would be good to share that fix for those that had a custom OS theme.
