### ISSUE TITLE
How to disable dark background?

### ISSUE THREAD

**Issue by tungmilan** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#20]
Hi Izheil,

Thanks for the quick fix for Firefox 62! However, the last update broke my Firefox settings. Before that, I just used files in the folder `Scrollbars & tooltips dark theme` with Firefox theme `Dream of Waves`. Now I have to use `userContent.css` & `userChrome.css` from folder `Full theme (except scrollbars)` which resulted in not-so-good looking when opening local `html` files.

![ff_html_local](https://user-images.githubusercontent.com/6590141/45191646-5670b480-b1f9-11e8-8f03-4fb06c94c7de.PNG)

I commented out line #71-72 in `userContent.css` but it made other pages look worse while not solving the problem. For example this was how GitHub looked

![ff_gh](https://user-images.githubusercontent.com/6590141/45191706-a3ed2180-b1f9-11e8-980e-754f0ebc2e50.PNG)

How can I disable the dark theme/background completely? Can you add a section in the Readme for users who are only interested in multi-row tabs but not dark theme?

Thanks!

**Comment by Izheil** [comment]
I must have forgotten to add it, but now it's there!

You only need to create a new empty userChrome.css with the following lines:

<pre>/* DO NOT DELETE THIS LINE */
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

/* This enables the use of JS external files */
toolbarbutton#alltabs-button {
    -moz-binding: url("userChrome.xml#js")}</pre>

If you already have your own custom userChrome you won't need to add the namespace rule again. Only the toolbarbutton one along with userChrome.xml is needed.

**Comment by tungmilan** [comment]
Thank you!
