### ISSUE TITLE
Video guide not available

### ISSUE THREAD

**Issue by jgauthi** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#26]
Hi,

In this page: https://github.com/Izheil/Firefox-57-full-dark-theme-with-scrollbars/tree/master/Full%20theme%20(except%20scrollbars)

The video link is not available: "You can check a video guide here." --> https://youtu.be/z0o8DatRyjk

**Comment by Izheil** [comment]
Ah, sorry, I must have forgotten to update the link, it should be fixed now.

The video in question was --> [https://youtu.be/FHV1-LbX_Vo](https://youtu.be/FHV1-LbX_Vo)
