### ISSUE TITLE
Side Bar Bookmarks not colored

### ISSUE THREAD

**Issue by Allrick1** [Izheil/Firefox-57-full-dark-theme-with-scrollbars#27]
Hello,

Line 90 of the userchrome.css is not coloring the side bar bookmarks background to dark.  I was able to fix it by adding "#bookmarks-view" to line 779 of the same file.

**Comment by Izheil** [comment]
Hello,

It seems alright to me, but I'll add a general selector for all tabs on the sidebar (<code>.sidebar-placesTree</code>) just in case for others experiencing the same issue. Thanks for the input!

**Comment by Allrick1** [comment]
thanks!
